<?php

namespace Database\Seeders\Tenants;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $egyptCities = [
            ['governorate_id' => '1','name' => 'Samannoud'],
            ['governorate_id' => '1','name' => 'Tanta'],
            ['governorate_id' => '1','name' => 'Al Sanatah'],
            ['governorate_id' => '1','name' => 'Mahalla'],
            ['governorate_id' => '1','name' => 'Kafr El Zayat'],
            ['governorate_id' => '1','name' => 'Qatour'],
            ['governorate_id' => '1','name' => 'Zyfta'],
            ['governorate_id' => '1','name' => 'Basyoun'],
            ['governorate_id' => '1','name' => 'Bramah'],
            ['governorate_id' => '1','name' => 'Mete Habesh'],
            ['governorate_id' => '1','name' => 'Manshiet Janzour'],
            ['governorate_id' => '2','name' => 'Nasr City'],
            ['governorate_id' => '2','name' => 'Helwan'],
            ['governorate_id' => '2','name' => 'Maadi Gardens'],
            ['governorate_id' => '2','name' => 'Maadi'],
            ['governorate_id' => '2','name' => 'El Marge'],
            ['governorate_id' => '2','name' => 'Downtown'],
            ['governorate_id' => '2','name' => 'Ain Shams'],
            ['governorate_id' => '2','name' => 'El Sayedah zainb'],
            ['governorate_id' => '2','name' => 'Manil'],
            ['governorate_id' => '2','name' => 'Eain Sun'],
            ['governorate_id' => '2','name' => 'Shubra Al Khaimah'],
            ['governorate_id' => '2','name' => 'El Sharabiah'],
            ['governorate_id' => '2','name' => 'Shubra'],
            ['governorate_id' => '2','name' => 'El Mattaryah'],
            ['governorate_id' => '2','name' => 'Dar AISalaam'],
            ['governorate_id' => '2','name' => 'El Zayton'],
            ['governorate_id' => '2','name' => 'Faida Kamel'],
            ['governorate_id' => '2','name' => 'Heliopolis'],
            ['governorate_id' => '2','name' => 'Ezbet El Nakhl'],
            ['governorate_id' => '2','name' => 'Ain Sira'],
            ['governorate_id' => '2','name' => 'Ramses Square'],
            ['governorate_id' => '2','name' => 'Manshiet Nasser'],
            ['governorate_id' => '2','name' => 'El Khosose'],
            ['governorate_id' => '2','name' => 'Kasr El Ainy St'],
            ['governorate_id' => '2','name' => 'El Basateen'],
            ['governorate_id' => '2','name' => 'Arabs of Maadi'],
            ['governorate_id' => '2','name' => 'Mokattam'],
            ['governorate_id' => '2','name' => 'EL Mogharbkein'],
            ['governorate_id' => '2','name' => 'Abbasiya'],
            ['governorate_id' => '2','name' => 'El Salam'],
            ['governorate_id' => '2','name' => 'Hadaek Al Kbba'],
            ['governorate_id' => '2','name' => 'Al-Daher'],
            ['governorate_id' => '2','name' => 'Al Zawyah'],
            ['governorate_id' => '2','name' => 'EL Darrasah'],
            ['governorate_id' => '2','name' => 'El Sayedah Sakina'],
            ['governorate_id' => '2','name' => 'Ahmed Zaki'],
            ['governorate_id' => '2','name' => 'al-Emam Al Shafi'],
            ['governorate_id' => '2','name' => 'Bulaq Abu Al-Ela'],
            ['governorate_id' => '2','name' => 'Al Sharafah'],
            ['governorate_id' => '2','name' => 'Mansheyat Al Bakry'],
            ['governorate_id' => '2','name' => 'El Sayedah Aisha'],
            ['governorate_id' => '3','name' => 'Shbeen El Koom'],
            ['governorate_id' => '3','name' => 'Ashmoun'],
            ['governorate_id' => '3','name' => 'Al Shohadaa'],
            ['governorate_id' => '3','name' => 'Menouf'],
            ['governorate_id' => '3','name' => 'Tala'],
            ['governorate_id' => '3','name' => 'Quesna'],
            ['governorate_id' => '3','name' => 'Berket Al Sabaa'],
            ['governorate_id' => '3','name' => 'Al-Bajur'],
            ['governorate_id' => '3','name' => 'Mlig'],
            ['governorate_id' => '3','name' => 'Patanon'],
            ['governorate_id' => '3','name' => 'Astanha'],
            ['governorate_id' => '4','name' => 'El Dokki'],
            ['governorate_id' => '4','name' => 'Al-Warraq'],
            ['governorate_id' => '4','name' => 'Bulaq'],
            ['governorate_id' => '4','name' => 'Aowseem'],
            ['governorate_id' => '4','name' => 'Al Barajeel Airport'],
            ['governorate_id' => '4','name' => 'Giza'],
            ['governorate_id' => '4','name' => 'Bashtil'],
            ['governorate_id' => '4','name' => 'Faisal'],
            ['governorate_id' => '4','name' => 'Barajil'],
            ['governorate_id' => '4','name' => 'Imbaba'],
            ['governorate_id' => '4','name' => 'El Haram'],
            ['governorate_id' => '4','name' => 'El Mohandseen'],
            ['governorate_id' => '4','name' => 'Wardan'],
            ['governorate_id' => '4','name' => 'Al Rahaway'],
            ['governorate_id' => '4','name' => 'Embaba'],
            ['governorate_id' => '4','name' => 'October'],
            ['governorate_id' => '4','name' => 'Saqil'],
            ['governorate_id' => '4','name' => 'Menashe'],
            ['governorate_id' => '4','name' => 'Mansouriya'],
            ['governorate_id' => '4','name' => 'Kafr Hakim'],
            ['governorate_id' => '4','name' => 'Tanash'],
            ['governorate_id' => '4','name' => 'Bartas'],
            ['governorate_id' => '4','name' => 'Nekla'],
            ['governorate_id' => '4','name' => 'Bahormos'],
            ['governorate_id' => '4','name' => 'Burgash'],
            ['governorate_id' => '5','name' => 'Image'],
            ['governorate_id' => '5','name' => 'Sherbein'],
            ['governorate_id' => '5','name' => 'Sinbellaween'],
            ['governorate_id' => '5','name' => 'Dekernes'],
            ['governorate_id' => '5','name' => 'Belqas'],
            ['governorate_id' => '5','name' => 'El Manzalah'],
            ['governorate_id' => '5','name' => 'Mina Al-Nasr'],
            ['governorate_id' => '5','name' => 'Nebaroo'],
            ['governorate_id' => '5','name' => 'Meet Ghamre'],
            ['governorate_id' => '5','name' => 'Talkha'],
            ['governorate_id' => '5','name' => 'Aga'],
            ['governorate_id' => '5','name' => 'El Gammaliah'],
            ['governorate_id' => '5','name' => 'El Mataryah'],
            ['governorate_id' => '5','name' => 'El Dakahlya'],
            ['governorate_id' => '6','name' => 'Al Fateh'],
            ['governorate_id' => '6','name' => 'Asyut'],
            ['governorate_id' => '6','name' => 'Abnob'],
            ['governorate_id' => '6','name' => 'Slim coast'],
            ['governorate_id' => '6','name' => 'Abu Tig'],
            ['governorate_id' => '6','name' => 'Dayrut'],
            ['governorate_id' => '6','name' => 'Al Ghanayem'],
            ['governorate_id' => '6','name' => 'Al Qusia'],
            ['governorate_id' => '6','name' => 'Manfalut'],
            ['governorate_id' => '6','name' => 'Al Badary'],
            ['governorate_id' => '6','name' => 'Sadfaa'],
            ['governorate_id' => '6','name' => 'Abutig'],
            ['governorate_id' => '7','name' => 'Marsa Matrouh'],
            ['governorate_id' => '7','name' => 'Al Hammam'],
            ['governorate_id' => '7','name' => 'Al Dabbaah'],
            ['governorate_id' => '8','name' => 'Mashtoul'],
            ['governorate_id' => '8','name' => 'Belbeis'],
            ['governorate_id' => '8','name' => 'Awlad Saqr'],
            ['governorate_id' => '8','name' => 'Husseiniyah'],
            ['governorate_id' => '8','name' => 'Kafr Saqr'],
            ['governorate_id' => '8','name' => 'Abu Kabir'],
            ['governorate_id' => '8','name' => 'Derb Najm'],
            ['governorate_id' => '8','name' => 'Hehya'],
            ['governorate_id' => '8','name' => 'Abu Hammad'],
            ['governorate_id' => '8','name' => 'Faqous'],
            ['governorate_id' => '8','name' => 'Al Aasher'],
            ['governorate_id' => '8','name' => 'El Ebrahimia'],
            ['governorate_id' => '8','name' => 'Zagazig'],
            ['governorate_id' => '8','name' => 'Minya El Kamh'],
            ['governorate_id' => '8','name' => 'Al Tebyah'],
            ['governorate_id' => '8','name' => 'Al-Husseiniyah'],
            ['governorate_id' => '8','name' => 'Al Qanayat'],
            ['governorate_id' => '8','name' => 'Anshas'],
            ['governorate_id' => '9','name' => 'Toukh'],
            ['governorate_id' => '9','name' => 'Kafr Shukr'],
            ['governorate_id' => '9','name' => 'Shubra Al Khaimah'],
            ['governorate_id' => '9','name' => 'Banha'],
            ['governorate_id' => '9','name' => 'Al Qanater'],
            ['governorate_id' => '9','name' => 'Shibin Al Qanater'],
            ['governorate_id' => '9','name' => 'Khanka'],
            ['governorate_id' => '9','name' => 'Qalyub'],
            ['governorate_id' => '10','name' => 'El Wasta'],
            ['governorate_id' => '10','name' => 'Semsta'],
            ['governorate_id' => '10','name' => 'Fashion'],
            ['governorate_id' => '10','name' => 'Ihnasia'],
            ['governorate_id' => '10','name' => 'Bush'],
            ['governorate_id' => '10','name' => 'Bani Sweif'],
            ['governorate_id' => '10','name' => 'Baba'],
            ['governorate_id' => '11','name' => 'Kafr El-Sheikh'],
            ['governorate_id' => '11','name' => 'Qulleen'],
            ['governorate_id' => '11','name' => 'Desouk'],
            ['governorate_id' => '11','name' => 'Hamul'],
            ['governorate_id' => '11','name' => 'Sir Salm'],
            ['governorate_id' => '11','name' => 'Bella'],
            ['governorate_id' => '11','name' => 'Riyadh'],
            ['governorate_id' => '11','name' => 'Baltim'],
            ['governorate_id' => '11','name' => 'Fuh'],
            ['governorate_id' => '11','name' => 'Motobas'],
            ['governorate_id' => '11','name' => 'Burullus Tower'],
            ['governorate_id' => '12','name' => 'NagaaHammadi'],
            ['governorate_id' => '12','name' => 'Deshnah'],
            ['governorate_id' => '12','name' => 'Abo Tesht'],
            ['governorate_id' => '12','name' => 'Qus'],
            ['governorate_id' => '12','name' => 'Qaft'],
            ['governorate_id' => '12','name' => 'Naqqadah'],
            ['governorate_id' => '12','name' => 'Farshout'],
            ['governorate_id' => '12','name' => 'Qena'],
            ['governorate_id' => '13','name' => 'Manya'],
            ['governorate_id' => '13','name' => 'Mattai'],
            ['governorate_id' => '13','name' => 'Mallawy'],
            ['governorate_id' => '13','name' => 'Abu Qurqas'],
            ['governorate_id' => '13','name' => 'Bani Mazar'],
            ['governorate_id' => '13','name' => 'Smalut'],
            ['governorate_id' => '13','name' => 'Mughaghah'],
            ['governorate_id' => '13','name' => 'Aladawah'],
            ['governorate_id' => '13','name' => 'Dermawas'],
            ['governorate_id' => '14','name' => 'Port Said'],
            ['governorate_id' => '15','name' => 'Kom Ombo'],
            ['governorate_id' => '15','name' => 'Adfu'],
            ['governorate_id' => '15','name' => 'Aswan'],
            ['governorate_id' => '15','name' => 'Draw'],
            ['governorate_id' => '15','name' => 'Nasr El Noubah'],
            ['governorate_id' => '16','name' => 'Al-Mansheya'],
            ['governorate_id' => '16','name' => 'Al Qabbary'],
            ['governorate_id' => '16','name' => 'Alras El Soudah'],
            ['governorate_id' => '16','name' => 'El Raml Station'],
            ['governorate_id' => '16','name' => 'Ezbet Mohsen'],
            ['governorate_id' => '16','name' => 'Ghobryal'],
            ['governorate_id' => '16','name' => 'Sidi Gaber'],
            ['governorate_id' => '16','name' => 'El Ebrahimia'],
            ['governorate_id' => '16','name' => 'Sidi Beshr'],
            ['governorate_id' => '16','name' => 'Azarita'],
            ['governorate_id' => '16','name' => 'Mandara'],
            ['governorate_id' => '16','name' => 'Al Asafrah'],
            ['governorate_id' => '16','name' => 'Hanoville'],
            ['governorate_id' => '16','name' => 'Miami'],
            ['governorate_id' => '16','name' => 'Bacchus'],
            ['governorate_id' => '16','name' => 'Al-Bitash'],
            ['governorate_id' => '16','name' => 'Sporting'],
            ['governorate_id' => '16','name' => 'Al-Wardian'],
            ['governorate_id' => '16','name' => 'Al Zahryah'],
            ['governorate_id' => '16','name' => 'El Mallahah'],
            ['governorate_id' => '16','name' => 'Al Amriya'],
            ['governorate_id' => '16','name' => 'Abukir'],
            ['governorate_id' => '16','name' => 'El Hadarah'],
            ['governorate_id' => '16','name' => 'Abees'],
            ['governorate_id' => '16','name' => 'Camp Shezar'],
            ['governorate_id' => '16','name' => 'El Daraysah'],
            ['governorate_id' => '16','name' => 'Wingate'],
            ['governorate_id' => '16','name' => 'Cleopatra'],
            ['governorate_id' => '16','name' => 'Muharram Bey'],
            ['governorate_id' => '16','name' => 'Mustafa Kamel'],
            ['governorate_id' => '16','name' => 'Maamoura'],
            ['governorate_id' => '16','name' => 'Mahtet Misr'],
            ['governorate_id' => '16','name' => 'Burj Al Arab'],
            ['governorate_id' => '16','name' => 'Glim'],
            ['governorate_id' => '16','name' => 'Abu Sulaiman'],
            ['governorate_id' => '16','name' => 'Khorshid'],
            ['governorate_id' => '16','name' => 'Bolqa'],
            ['governorate_id' => '16','name' => 'Shuds'],
            ['governorate_id' => '16','name' => 'El Seyouf'],
            ['governorate_id' => '16','name' => 'Vectorya'],
            ['governorate_id' => '16','name' => 'Ghait El Enab'],
            ['governorate_id' => '16','name' => 'Salihiya'],
            ['governorate_id' => '16','name' => 'Ezbet El Matar'],
            ['governorate_id' => '16','name' => 'El Dekhielah'],
            ['governorate_id' => '16','name' => 'Rushdie'],
            ['governorate_id' => '16','name' => 'Ezbet Sakina'],
            ['governorate_id' => '16','name' => 'Ragheb'],
            ['governorate_id' => '16','name' => 'El Metras'],
            ['governorate_id' => '16','name' => 'Tabia'],
            ['governorate_id' => '16','name' => 'Karmoz'],
            ['governorate_id' => '16','name' => 'Al-Zawayda'],
            ['governorate_id' => '16','name' => 'Mandara Bahri'],
            ['governorate_id' => '16','name' => 'The bakatoshi'],
            ['governorate_id' => '16','name' => 'Bahary'],
            ['governorate_id' => '17','name' => 'Damanhour'],
            ['governorate_id' => '17','name' => 'Kafr El Dawar'],
            ['governorate_id' => '17','name' => 'Rashid'],
            ['governorate_id' => '17','name' => 'Itay Baroud'],
            ['governorate_id' => '17','name' => 'Koom Hamada'],
            ['governorate_id' => '17','name' => 'Housh Issa'],
            ['governorate_id' => '17','name' => 'El Dalangat'],
            ['governorate_id' => '17','name' => 'Abu Homs'],
            ['governorate_id' => '17','name' => 'Abu Al-Matamir'],
            ['governorate_id' => '17','name' => 'Edko'],
            ['governorate_id' => '17','name' => 'Shubrakhit'],
            ['governorate_id' => '17','name' => 'Wadi Natrun'],
            ['governorate_id' => '17','name' => 'Nubaria'],
            ['governorate_id' => '17','name' => 'Badr Center'],
            ['governorate_id' => '17','name' => 'Mahmoudiya'],
            ['governorate_id' => '17','name' => 'Abu Homs'],
            ['governorate_id' => '17','name' => 'Sadat'],
            ['governorate_id' => '17','name' => 'Al-Khatahtbeh'],
            ['governorate_id' => '17','name' => 'Adfeena'],
            ['governorate_id' => '18','name' => 'El Tal El Kebeer'],
            ['governorate_id' => '18','name' => 'Ismailia'],
            ['governorate_id' => '18','name' => 'Fayed'],
            ['governorate_id' => '18','name' => 'Abu Sawyer'],
            ['governorate_id' => '18','name' => 'El Qantarah'],
            ['governorate_id' => '18','name' => 'Abu Khalifa'],
            ['governorate_id' => '18','name' => 'Abu Atwa'],
            ['governorate_id' => '18','name' => 'El Qasaseen'],
            ['governorate_id' => '18','name' => 'Serapeum'],
            ['governorate_id' => '18','name' => 'Arayesh Misr'],
            ['governorate_id' => '18','name' => 'El Thalathiny'],
            ['governorate_id' => '18','name' => 'Neheeshah'],
            ['governorate_id' => '19','name' => 'Damietta'],
            ['governorate_id' => '19','name' => 'Kafr Saad'],
            ['governorate_id' => '19','name' => 'Farscore'],
            ['governorate_id' => '19','name' => 'Al Zarqa'],
            ['governorate_id' => '19','name' => 'Ras Al Bar'],
            ['governorate_id' => '19','name' => 'Kafr El Bateekh'],
            ['governorate_id' => '20','name' => 'Gerga'],
            ['governorate_id' => '20','name' => 'Maragheh'],
            ['governorate_id' => '20','name' => 'Belina'],
            ['governorate_id' => '20','name' => 'Dar AISalaam'],
            ['governorate_id' => '20','name' => 'Tama'],
            ['governorate_id' => '20','name' => 'Sohag'],
            ['governorate_id' => '20','name' => 'Taha'],
            ['governorate_id' => '20','name' => 'Akhmim'],
            ['governorate_id' => '20','name' => 'Pardis'],
            ['governorate_id' => '20','name' => 'Kaqtalah'],
            ['governorate_id' => '20','name' => 'El Monshaah'],
            ['governorate_id' => '20','name' => 'Maragha'],
            ['governorate_id' => '21','name' => 'Fayoum'],
            ['governorate_id' => '21','name' => 'Abshway'],
            ['governorate_id' => '21','name' => 'Snores'],
            ['governorate_id' => '21','name' => 'Atsa'],
            ['governorate_id' => '21','name' => 'Tamiya'],
            ['governorate_id' => '22','name' => 'Arish'],
            ['governorate_id' => '23','name' => 'Luxor'],
            ['governorate_id' => '23','name' => 'ArmentEl Heet'],
            ['governorate_id' => '23','name' => 'Asna'],
            ['governorate_id' => '23','name' => 'Arment El Wabarat'],
            ['governorate_id' => '24','name' => 'Dakhla'],
            ['governorate_id' => '24','name' => 'Khargah'],
            ['governorate_id' => '25','name' => 'Suez'],
            ['governorate_id' => '26','name' => 'Hurghada']
          ];
          
$saCities = [
    ['governorate_id' => '27','name' => 'Riyadh'],
    ['governorate_id' => '27','name' => 'Diriyah'],
    ['governorate_id' => '27','name' => 'Al Kharj'],
    ['governorate_id' => '27','name' => 'Dawadmi'],
    ['governorate_id' => '27','name' => 'El Magmaah'],
    ['governorate_id' => '27','name' => 'El Quayeyha'],
    ['governorate_id' => '27','name' => 'Aflaj'],
    ['governorate_id' => '27','name' => 'Wadi Al-Dawasir'],
    ['governorate_id' => '27','name' => 'Zulfi'],
    ['governorate_id' => '27','name' => 'Shakraa'],
    ['governorate_id' => '27','name' => 'Hotat Bani Tamim'],
    ['governorate_id' => '27','name' => 'Afif'],
    ['governorate_id' => '27','name' => 'Ghat'],
    ['governorate_id' => '27','name' => 'El Saliel'],
    ['governorate_id' => '27','name' => 'Dharma'],
    ['governorate_id' => '27','name' => 'Al-Muzahmiyah'],
    ['governorate_id' => '27','name' => 'Rammah'],
    ['governorate_id' => '27','name' => 'Thadq'],
    ['governorate_id' => '27','name' => 'Harimala'],
    ['governorate_id' => '27','name' => 'El Harrek'],
    ['governorate_id' => '27','name' => 'Marrat'],
    ['governorate_id' => '27','name' => 'Al Reen'],
    ['governorate_id' => '27','name' => 'Al dalm'],
    ['governorate_id' => '28','name' => 'Makkah'],
    ['governorate_id' => '28','name' => 'Gaddah'],
    ['governorate_id' => '28','name' => 'Taif'],
    ['governorate_id' => '28','name' => 'Qunfudhah'],
    ['governorate_id' => '28','name' => 'Allaieth'],
    ['governorate_id' => '28','name' => 'Rabigh'],
    ['governorate_id' => '28','name' => 'Kholies'],
    ['governorate_id' => '28','name' => 'Al Khorma'],
    ['governorate_id' => '28','name' => 'Rania'],
    ['governorate_id' => '28','name' => 'Al Torba'],
    ['governorate_id' => '28','name' => 'Al-Jamoum'],
    ['governorate_id' => '28','name' => 'Al Kamel'],
    ['governorate_id' => '28','name' => 'Al Moayeh'],
    ['governorate_id' => '28','name' => 'Maysan'],
    ['governorate_id' => '28','name' => 'Adom'],
    ['governorate_id' => '28','name' => 'Al Oraydad'],
    ['governorate_id' => '28','name' => 'Bahra'],
    ['governorate_id' => '29','name' => 'AL Madinah AL Munawwarah'],
    ['governorate_id' => '29','name' => 'Yanboaa'],
    ['governorate_id' => '29','name' => 'Al Olaa'],
    ['governorate_id' => '29','name' => 'Al Mahd'],
    ['governorate_id' => '29','name' => 'Hanakia'],
    ['governorate_id' => '29','name' => 'Badr'],
    ['governorate_id' => '29','name' => 'Khaibar'],
    ['governorate_id' => '29','name' => 'Ais'],
    ['governorate_id' => '29','name' => 'Wadi Al Faraa'],
    ['governorate_id' => '30','name' => 'Buraidah'],
    ['governorate_id' => '30','name' => 'Unayzah'],
    ['governorate_id' => '30','name' => 'Al Ros'],
    ['governorate_id' => '30','name' => 'Al Moznab'],
    ['governorate_id' => '30','name' => 'Al-Bakiriya'],
    ['governorate_id' => '30','name' => 'El Badaeaa'],
    ['governorate_id' => '30','name' => 'Al Asyaah'],
    ['governorate_id' => '30','name' => 'Nabhaniyya'],
    ['governorate_id' => '30','name' => 'Al Shamasyah'],
    ['governorate_id' => '30','name' => 'Eyoun El Gawaa'],
    ['governorate_id' => '30','name' => 'Riyadh Al-Khabara'],
    ['governorate_id' => '30','name' => 'Oqelet El Soqour'],
    ['governorate_id' => '30','name' => 'Daryah'],
    ['governorate_id' => '31','name' => 'Dammam'],
    ['governorate_id' => '31','name' => 'Al Ahsaa'],
    ['governorate_id' => '31','name' => 'Hafar Al-Batin'],
    ['governorate_id' => '31','name' => 'Jubail'],
    ['governorate_id' => '31','name' => 'Qatif'],
    ['governorate_id' => '31','name' => 'Al Khobor'],
    ['governorate_id' => '31','name' => 'Khafji'],
    ['governorate_id' => '31','name' => 'Raas Tanourah'],
    ['governorate_id' => '31','name' => 'Baqeq'],
    ['governorate_id' => '31','name' => 'Nairiyah'],
    ['governorate_id' => '31','name' => 'Qaryet Al Oliaa'],
    ['governorate_id' => '31','name' => 'Al Adeed'],
    ['governorate_id' => '31','name' => 'Al Baydaa'],
    ['governorate_id' => '32','name' => 'Abha'],
    ['governorate_id' => '32','name' => 'Khamis Mushait'],
    ['governorate_id' => '32','name' => 'Beesha'],
    ['governorate_id' => '32','name' => 'Al-Namas'],
    ['governorate_id' => '32','name' => 'Mahayil Asir'],
    ['governorate_id' => '32','name' => 'Dhahran South'],
    ['governorate_id' => '32','name' => 'Tathleeth'],
    ['governorate_id' => '32','name' => 'Sarat Obeida'],
    ['governorate_id' => '32','name' => 'Raggal Almaa'],
    ['governorate_id' => '32','name' => 'Belqarn'],
    ['governorate_id' => '32','name' => 'Ahad Rufaida'],
    ['governorate_id' => '32','name' => 'Majarda'],
    ['governorate_id' => '32','name' => 'El Baraq'],
    ['governorate_id' => '32','name' => 'Bareq'],
    ['governorate_id' => '32','name' => 'Tannomah'],
    ['governorate_id' => '32','name' => 'Taryeb'],
    ['governorate_id' => '32','name' => 'Al Hargah'],
    ['governorate_id' => '33','name' => 'Tabuk'],
    ['governorate_id' => '33','name' => 'Al wageh'],
    ['governorate_id' => '33','name' => 'Duba'],
    ['governorate_id' => '33','name' => 'Taima'],
    ['governorate_id' => '33','name' => 'Amlag'],
    ['governorate_id' => '33','name' => 'Haqle'],
    ['governorate_id' => '33','name' => 'Al Badaa'],
    ['governorate_id' => '34','name' => 'Hail'],
    ['governorate_id' => '34','name' => 'Baqaa'],
    ['governorate_id' => '34','name' => 'Al Ghazalah'],
    ['governorate_id' => '34','name' => 'Al Shanan'],
    ['governorate_id' => '34','name' => 'Al Haet'],
    ['governorate_id' => '34','name' => 'Sulaimi'],
    ['governorate_id' => '34','name' => 'Al-Shamli'],
    ['governorate_id' => '34','name' => 'Mooqaq'],
    ['governorate_id' => '34','name' => 'Somairaa'],
    ['governorate_id' => '35','name' => 'Arar'],
    ['governorate_id' => '35','name' => 'Rafha'],
    ['governorate_id' => '35','name' => 'Tareef'],
    ['governorate_id' => '35','name' => 'Al-Awiqila'],
    ['governorate_id' => '36','name' => 'Jazan'],
    ['governorate_id' => '36','name' => 'Sebya'],
    ['governorate_id' => '36','name' => 'Abu Arish'],
    ['governorate_id' => '36','name' => 'Samtah'],
    ['governorate_id' => '36','name' => 'Pesh'],
    ['governorate_id' => '36','name' => 'Al Darb'],
    ['governorate_id' => '36','name' => 'Al Harth'],
    ['governorate_id' => '36','name' => 'Domt'],
    ['governorate_id' => '36','name' => 'Al Reeth'],
    ['governorate_id' => '36','name' => 'Forsan'],
    ['governorate_id' => '36','name' => 'Al Daael'],
    ['governorate_id' => '36','name' => 'Alaardah'],
    ['governorate_id' => '36','name' => 'Ahod Al Masarha'],
    ['governorate_id' => '36','name' => 'Al Aydaby'],
    ['governorate_id' => '36','name' => 'Faifa'],
    ['governorate_id' => '36','name' => 'Al Twaal'],
    ['governorate_id' => '36','name' => 'Hroob'],
    ['governorate_id' => '37','name' => 'Najran'],
    ['governorate_id' => '37','name' => 'Sharurah'],
    ['governorate_id' => '37','name' => 'Haboonah'],
    ['governorate_id' => '37','name' => 'Badr Al-Janoub'],
    ['governorate_id' => '37','name' => 'Yadmah'],
    ['governorate_id' => '37','name' => 'Thar'],
    ['governorate_id' => '37','name' => 'Khabbash'],
    ['governorate_id' => '38','name' => 'Al-Baha'],
    ['governorate_id' => '38','name' => 'Beljurashi'],
    ['governorate_id' => '38','name' => 'Mandaq'],
    ['governorate_id' => '38','name' => 'El Makhwah'],
    ['governorate_id' => '38','name' => 'Qalwa'],
    ['governorate_id' => '38','name' => 'Al Aqeeq'],
    ['governorate_id' => '38','name' => 'Al Qoraa'],
    ['governorate_id' => '38','name' => 'Ghamed El Zanad'],
    ['governorate_id' => '38','name' => 'Al Hajrah'],
    ['governorate_id' => '38','name' => 'Bani Hassan'],
    ['governorate_id' => '39','name' => 'Sakaka'],
    ['governorate_id' => '39','name' => 'Qurayyat'],
    ['governorate_id' => '39','name' => 'Duma Jandal'],
    ['governorate_id' => '39','name' => 'Tabarjal']
  ];
  

          City::insert($saCities); 
        
    }
}
